# This file was generated by GoReleaser. DO NOT EDIT.
cask "bolty" do
  version "0.4.2"

  on_macos do
    on_intel do
      sha256 "02d6da59a8487649b1f7ec64b5fb69420e3fb8b9e4256b6a436491380c431aaf"
      url "https://github.com/emqmalte/bolty/releases/download/v#{version}/bolty_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "eb2fa80ae7743f4a14eaba079d3e13a46a60e37860a80bac077a05afb48b6d02"
      url "https://github.com/emqmalte/bolty/releases/download/v#{version}/bolty_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "9b27de24218bd870643228161217249899ed87bc6235840fbf86ceb9da6bf96a"
      url "https://github.com/emqmalte/bolty/releases/download/v#{version}/bolty_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "9320233dcdd112e876776b8ab25c4a4c40f528a251ccdfbb6a357646e836b56d"
      url "https://github.com/emqmalte/bolty/releases/download/v#{version}/bolty_#{version}_linux_arm64.tar.gz"
    end
  end

  name "bolty"
  desc "Inject Passbolt secrets into local configuration files"
  homepage "https://github.com/emqmalte/bolty"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bolty"

  generate_completions_from_executable "bolty",
    base_name: "bolty",
    shell_parameter_format: :cobra,
    shells: [:bash, :zsh, :fish]

  # No zap stanza required

end
