# This file was generated by GoReleaser. DO NOT EDIT.
cask "bolty" do
  version "0.4.1"

  on_macos do
    on_intel do
      sha256 "927f5e1a922ac5cbc0be17127223c4eed63380e51e67d4b28af3c306491bc174"
      url "https://github.com/emqmalte/bolty/releases/download/v#{version}/bolty_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "e21c6d166672f4e95166fee5f03d6a9f934fd3cb8bc5e3bec72541bfc3b3ac29"
      url "https://github.com/emqmalte/bolty/releases/download/v#{version}/bolty_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "b9b73928ca50917467bfe34eedcc323eba6779942a014cb60357707611822e99"
      url "https://github.com/emqmalte/bolty/releases/download/v#{version}/bolty_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "a89662001b41c271a8071feb2c0e5dda8dd17131b616d663a502b417b5e24051"
      url "https://github.com/emqmalte/bolty/releases/download/v#{version}/bolty_#{version}_linux_arm64.tar.gz"
    end
  end

  name "bolty"
  desc "Inject Passbolt secrets into local configuration files"
  homepage "https://github.com/emqmalte/bolty"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bolty"

  generate_completions_from_executable "bolty",
    base_name: "bolty",
    shell_parameter_format: :cobra,
    shells: [:bash, :zsh, :fish]

  # No zap stanza required

end
