# This file was generated by GoReleaser. DO NOT EDIT.
cask "bolty" do
  version "0.3.2"

  on_macos do
    on_intel do
      sha256 "fa812c7fcae05b473952f445a4430498c80cdef14b9cb1a4cf8c6d7b1f677ae6"
      url "https://github.com/emqmalte/bolty/releases/download/v#{version}/bolty_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "9028218fe0eb745b914b188e2bd769a5d8bf919575017ddbd7a583900e1a9687"
      url "https://github.com/emqmalte/bolty/releases/download/v#{version}/bolty_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "a63d33e04b5ea95abdd48168e98184b1f50daa91a8e8365bba848af57d961eac"
      url "https://github.com/emqmalte/bolty/releases/download/v#{version}/bolty_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "4849a99b904e2145998d7238d9a1383b0efca1783d86cfa1865e82f34fa65e8f"
      url "https://github.com/emqmalte/bolty/releases/download/v#{version}/bolty_#{version}_linux_arm64.tar.gz"
    end
  end

  name "bolty"
  desc "Inject Passbolt secrets into local configuration files"
  homepage "https://github.com/emqmalte/bolty"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bolty"

  generate_completions_from_executable "bolty",
    base_name: "bolty",
    shell_parameter_format: :cobra,
    shells: [:bash, :zsh, :fish]

  # No zap stanza required

end
